/**
 * builtinData.ts
 * 內建預設關卡地圖、武將與敵兵靜態數據
 * 確保在離線、低頻寬或 GAS 尚未載入時，能夠秒開即玩且擁有完整數值體驗
 */

import { WaveConfigData } from "./WaveManager";
import { HeroConfigData, HeroStateData } from "./entities/HeroEntity";
import { EnemyConfigData } from "./entities/EnemyEntity";

export interface StageData {
  map_id: string;
  chapter: number;
  name: string;
  unlock_stage: string;
  path_json: any;
  waves: WaveConfigData[];
}

export const BUILTIN_HEROES_CONFIG: HeroConfigData[] = [
  {
    hero_id: "hero_ma_chao",
    name: "馬超",
    job: "cavalry",
    attack_range: 2.2,
    attack_speed: 1.0,
    atk_growth: 15,
    def_growth: 8,
    hp_growth: 120,
    image: "hero_ma_chao.webp",
    attack_image: "hero_ma_chao_atk.webp",
  },
  {
    hero_id: "hero_zhao_yun",
    name: "趙雲",
    job: "infantry",
    attack_range: 1.8,
    attack_speed: 0.9,
    atk_growth: 14,
    def_growth: 10,
    hp_growth: 110,
    image: "hero_zhao_yun.webp",
    attack_image: "hero_zhao_yun_atk.webp",
  },
  {
    hero_id: "hero_huang_zhong",
    name: "黃忠",
    job: "archer",
    attack_range: 3.2,
    attack_speed: 1.1,
    atk_growth: 18,
    def_growth: 6,
    hp_growth: 90,
    image: "hero_huang_zhong.webp",
    attack_image: "hero_huang_zhong_atk.webp",
  },
  {
    hero_id: "hero_zhou_yu",
    name: "周瑜",
    job: "mage",
    attack_range: 2.5,
    attack_speed: 1.3,
    atk_growth: 20,
    def_growth: 7,
    hp_growth: 85,
    image: "hero_zhou_yu.webp",
    attack_image: "hero_zhou_yu_atk.webp",
  },
  {
    hero_id: "hero_guan_yu",
    name: "關羽",
    job: "cavalry",
    attack_range: 2.2,
    attack_speed: 1.2,
    atk_growth: 22,
    def_growth: 12,
    hp_growth: 140,
    image: "hero_guan_yu.webp",
    attack_image: "hero_guan_yu_atk.webp",
  },
  {
    hero_id: "hero_liu_bei",
    name: "劉備",
    job: "infantry",
    attack_range: 2.0,
    attack_speed: 1.0,
    atk_growth: 12,
    def_growth: 15,
    hp_growth: 160,
    image: "hero_liu_bei.webp",
    attack_image: "hero_liu_bei_atk.webp",
  },
  {
    hero_id: "hero_zhang_fei",
    name: "張飛",
    job: "infantry",
    attack_range: 1.9,
    attack_speed: 1.1,
    atk_growth: 24,
    def_growth: 11,
    hp_growth: 150,
    image: "hero_zhang_fei.webp",
    attack_image: "hero_zhang_fei_atk.webp",
  },
  {
    hero_id: "hero_wei_yan",
    name: "魏延",
    job: "infantry",
    attack_range: 1.8,
    attack_speed: 0.95,
    atk_growth: 16,
    def_growth: 9,
    hp_growth: 130,
    image: "hero_wei_yan.webp",
    attack_image: "hero_wei_yan_atk.webp",
  },
  {
    hero_id: "hero_cao_cao",
    name: "曹操",
    job: "cavalry",
    attack_range: 2.4,
    attack_speed: 1.0,
    atk_growth: 16,
    def_growth: 13,
    hp_growth: 145,
    image: "hero_cao_cao.webp",
    attack_image: "hero_cao_cao_atk.webp",
  },
  {
    hero_id: "hero_xia_hou_dun",
    name: "夏侯惇",
    job: "infantry",
    attack_range: 1.8,
    attack_speed: 1.1,
    atk_growth: 18,
    def_growth: 14,
    hp_growth: 155,
    image: "hero_xia_hou_dun.webp",
    attack_image: "hero_xia_hou_dun_atk.webp",
  },
  {
    hero_id: "hero_liao_hua",
    name: "廖化",
    job: "infantry",
    attack_range: 1.8,
    attack_speed: 1.0,
    atk_growth: 13,
    def_growth: 11,
    hp_growth: 125,
    image: "hero_liao_hua.webp",
    attack_image: "hero_liao_hua_atk.webp",
  },
  {
    hero_id: "hero_yan_liang",
    name: "顏良",
    job: "cavalry",
    attack_range: 2.0,
    attack_speed: 1.15,
    atk_growth: 21,
    def_growth: 10,
    hp_growth: 135,
    image: "hero_yan_liang.webp",
    attack_image: "hero_yan_liang_atk.webp",
  },
  {
    hero_id: "hero_sun_shang_xiang",
    name: "孫尚香",
    job: "archer",
    attack_range: 2.8,
    attack_speed: 0.9,
    atk_growth: 17,
    def_growth: 7,
    hp_growth: 95,
    image: "hero_sun_shang_xiang.webp",
    attack_image: "hero_sun_shang_xiang_atk.webp",
  },
];

export const BUILTIN_ENEMIES_CONFIG: EnemyConfigData[] = [
  {
    enemy_id: "grunt_lv1",
    name: "黃巾小卒",
    hp: 120,
    speed: 65,
    atk: 15,
    movement_type: "ground",
    image: "enemy_grunt1.webp",
    attack_image: "enemy_grunt1_atk.webp",
  },
  {
    enemy_id: "grunt_lv2",
    name: "黃巾精銳",
    hp: 240,
    speed: 70,
    atk: 25,
    movement_type: "ground",
    image: "enemy_grunt2.webp",
    attack_image: "enemy_grunt2_atk.webp",
  },
  {
    enemy_id: "cavalry_lv1",
    name: "黃巾騎兵",
    hp: 280,
    speed: 110,
    atk: 30,
    movement_type: "ground",
    image: "enemy_cavalry1.webp",
    attack_image: "enemy_cavalry1_atk.webp",
  },
  {
    enemy_id: "cavalry_lv2",
    name: "突騎精兵",
    hp: 450,
    speed: 115,
    atk: 45,
    movement_type: "ground",
    image: "enemy_cavalry2.webp",
    attack_image: "enemy_cavalry2_atk.webp",
  },
  {
    enemy_id: "siege_lv1",
    name: "機關衝車",
    hp: 800,
    speed: 45,
    atk: 60,
    movement_type: "ground",
    image: "enemy_siege1.webp",
    attack_image: "enemy_siege1_atk.webp",
  },
  {
    enemy_id: "flying_kite_lv1",
    name: "飛鳶斥候",
    hp: 160,
    speed: 85,
    atk: 20,
    movement_type: "flying",
    image: "enemy_grunt3.webp",
    attack_image: "enemy_grunt3_atk.webp",
  },
  {
    enemy_id: "flying_kite_lv2",
    name: "機關木鳶",
    hp: 350,
    speed: 90,
    atk: 35,
    movement_type: "flying",
    image: "enemy_siege3.webp",
    attack_image: "enemy_siege3_atk.webp",
  },
];

export const BUILTIN_STAGES: StageData[] = [
  {
    map_id: "chapter1_1",
    chapter: 1,
    name: "第一章 第1關 - 涿郡初陣",
    unlock_stage: "chapter1_1",
    path_json: {
      cols: 14,
      rows: 10,
      paths: {
        path_a: [
          [0, 3],
          [3, 3],
          [3, 7],
          [8, 7],
          [8, 2],
          [13, 2],
        ],
      },
      base: [13, 2],
      build_zones: [
        [2, 2],
        [4, 2],
        [2, 4],
        [4, 4],
        [4, 6],
        [7, 6],
        [7, 8],
        [9, 8],
        [7, 3],
        [9, 3],
        [9, 1],
        [11, 1],
        [11, 3],
      ],
      background_texture: "maps/bg_forest.webp",
    },
    waves: [
      {
        wave: 1,
        enemies: [
          { enemy_id: "grunt_lv1", count: 6, interval: 1.2, path: "path_a" },
        ],
      },
      {
        wave: 2,
        enemies: [
          { enemy_id: "grunt_lv1", count: 8, interval: 1.0, path: "path_a" },
          { enemy_id: "cavalry_lv1", count: 2, interval: 2.0, path: "path_a" },
        ],
      },
      {
        wave: 3,
        enemies: [
          { enemy_id: "grunt_lv2", count: 6, interval: 1.2, path: "path_a" },
          { enemy_id: "flying_kite_lv1", count: 4, interval: 1.5, path: "path_a" },
        ],
      },
      {
        wave: 4,
        enemies: [
          { enemy_id: "cavalry_lv1", count: 5, interval: 1.2, path: "path_a" },
          { enemy_id: "siege_lv1", count: 1, interval: 4.0, path: "path_a" },
          { enemy_id: "flying_kite_lv1", count: 3, interval: 1.5, path: "path_a" },
        ],
      },
      {
        wave: 5,
        enemies: [
          { enemy_id: "cavalry_lv2", count: 4, interval: 1.2, path: "path_a" },
          { enemy_id: "grunt_lv2", count: 8, interval: 0.8, path: "path_a" },
          { enemy_id: "siege_lv1", count: 2, interval: 3.5, path: "path_a" },
          { enemy_id: "flying_kite_lv2", count: 3, interval: 2.0, path: "path_a" },
        ],
      },
    ],
  },
  {
    map_id: "chapter1_2",
    chapter: 1,
    name: "第一章 第2關 - 界橋隘口",
    unlock_stage: "chapter1_2",
    path_json: {
      cols: 14,
      rows: 10,
      paths: {
        path_a: [
          [0, 2],
          [5, 2],
          [5, 5],
          [9, 5],
          [9, 8],
          [13, 8],
        ],
        path_b: [
          [0, 7],
          [4, 7],
          [4, 4],
          [10, 4],
          [10, 8],
          [13, 8],
        ],
      },
      base: [13, 8],
      build_zones: [
        [2, 1],
        [3, 1],
        [6, 2],
        [6, 3],
        [3, 5],
        [3, 6],
        [7, 4],
        [8, 4],
        [8, 6],
        [10, 6],
        [11, 7],
        [12, 7],
      ],
      background_texture: "maps/bg_forest1.webp",
    },
    waves: [
      {
        wave: 1,
        enemies: [
          { enemy_id: "grunt_lv1", count: 5, interval: 1.2, path: "path_a" },
          { enemy_id: "grunt_lv1", count: 5, interval: 1.2, path: "path_b" },
        ],
      },
      {
        wave: 2,
        enemies: [
          { enemy_id: "cavalry_lv1", count: 4, interval: 1.5, path: "path_a" },
          { enemy_id: "flying_kite_lv1", count: 4, interval: 1.5, path: "path_b" },
        ],
      },
      {
        wave: 3,
        enemies: [
          { enemy_id: "grunt_lv2", count: 6, interval: 1.0, path: "path_a" },
          { enemy_id: "cavalry_lv2", count: 4, interval: 1.5, path: "path_b" },
          { enemy_id: "siege_lv1", count: 2, interval: 3.0, path: "path_a" },
        ],
      },
      {
        wave: 4,
        enemies: [
          { enemy_id: "cavalry_lv2", count: 6, interval: 1.0, path: "path_a" },
          { enemy_id: "flying_kite_lv2", count: 5, interval: 1.2, path: "path_b" },
          { enemy_id: "siege_lv1", count: 3, interval: 2.5, path: "path_b" },
        ],
      },
    ],
  },
  {
    map_id: "chapter1_3",
    chapter: 1,
    name: "第一章 第3關 - 虎牢關血戰",
    unlock_stage: "chapter1_3",
    path_json: {
      cols: 14,
      rows: 10,
      paths: {
        path_a: [
          [0, 1],
          [11, 1],
          [11, 4],
          [2, 4],
          [2, 8],
          [13, 8],
        ],
      },
      base: [13, 8],
      build_zones: [
        [1, 0],
        [3, 0],
        [5, 0],
        [7, 0],
        [9, 0],
        [1, 2],
        [3, 2],
        [5, 2],
        [7, 2],
        [9, 2],
        [3, 5],
        [5, 5],
        [7, 5],
        [9, 5],
        [1, 7],
        [3, 7],
        [5, 7],
        [7, 7],
        [9, 7],
      ],
      background_texture: "maps/bg_forest2.webp",
    },
    waves: [
      {
        wave: 1,
        enemies: [
          { enemy_id: "grunt_lv1", count: 10, interval: 0.8, path: "path_a" },
        ],
      },
      {
        wave: 2,
        enemies: [
          { enemy_id: "cavalry_lv1", count: 6, interval: 1.0, path: "path_a" },
          { enemy_id: "flying_kite_lv1", count: 6, interval: 1.2, path: "path_a" },
        ],
      },
      {
        wave: 3,
        enemies: [
          { enemy_id: "cavalry_lv2", count: 6, interval: 1.0, path: "path_a" },
          { enemy_id: "siege_lv1", count: 2, interval: 2.5, path: "path_a" },
        ],
      },
      {
        wave: 4,
        enemies: [
          { enemy_id: "grunt_lv2", count: 12, interval: 0.6, path: "path_a" },
          { enemy_id: "flying_kite_lv2", count: 6, interval: 1.0, path: "path_a" },
        ],
      },
      {
        wave: 5,
        enemies: [
          { enemy_id: "cavalry_lv2", count: 8, interval: 0.8, path: "path_a" },
          { enemy_id: "siege_lv1", count: 4, interval: 2.0, path: "path_a" },
          { enemy_id: "flying_kite_lv2", count: 8, interval: 1.0, path: "path_a" },
        ],
      },
    ],
  },
];

export const DEFAULT_PLAYER_HEROES: HeroStateData[] = [
  { hero_id: "hero_ma_chao", level: 3, star: 1, atk: 120, def: 60, hp: 1200 },
  { hero_id: "hero_zhao_yun", level: 3, star: 1, atk: 110, def: 65, hp: 1150 },
  { hero_id: "hero_guan_yu", level: 4, star: 2, atk: 150, def: 75, hp: 1500 },
  { hero_id: "hero_zhang_fei", level: 3, star: 1, atk: 140, def: 70, hp: 1450 },
  { hero_id: "hero_zhou_yu", level: 3, star: 1, atk: 135, def: 55, hp: 1000 },
  { hero_id: "hero_huang_zhong", level: 3, star: 1, atk: 130, def: 50, hp: 950 },
  { hero_id: "hero_liu_bei", level: 3, star: 1, atk: 105, def: 80, hp: 1600 },
  { hero_id: "hero_wei_yan", level: 2, star: 1, atk: 115, def: 58, hp: 1250 },
  { hero_id: "hero_cao_cao", level: 3, star: 1, atk: 125, def: 72, hp: 1400 },
  { hero_id: "hero_xia_hou_dun", level: 2, star: 1, atk: 120, def: 68, hp: 1350 },
  { hero_id: "hero_liao_hua", level: 2, star: 1, atk: 100, def: 62, hp: 1200 },
  { hero_id: "hero_yan_liang", level: 2, star: 1, atk: 130, def: 60, hp: 1300 },
  { hero_id: "hero_sun_shang_xiang", level: 2, star: 1, atk: 125, def: 52, hp: 1050 },
];
